name: Python Pull Request Workflow
on: [pull_request]
jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: View poetry --help
        run: poetry --help
      - name: Install dependencies
        shell: bash
        run: python -m poetry install
      - name: Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          poetry run python manage.py test
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@latest
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}